import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
test('local HTTP service and persistent database',async()=>{const dir=await mkdtemp(join(tmpdir(),'veritas-'));const dbpath=join(dir,'test.sqlite');const child=spawn(process.execPath,[fileURLToPath(new URL('./server.ts',import.meta.url))],{env:{...process.env,PORT:'8793',VERITAS_OFFLINE:'1',VERITAS_DB_PATH:dbpath},stdio:['ignore','pipe','pipe']});try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Server startup timeout')),10000);child.stdout.on('data',data=>{if(data.toString().includes('ready')){clearTimeout(timer);resolve();}});child.on('exit',code=>{clearTimeout(timer);reject(new Error('Server exited '+code));});});
const base='http://127.0.0.1:8793';
const text='Solar panels convert sunlight into electrical energy using semiconductor materials that release electrons when exposed to incoming light particles. Batteries store surplus power for use during cloudy weather and evening hours.';
const request=(path:string,method='GET',body?:unknown)=>fetch(base+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
let r=await request('/api/sources');assert.equal(r.status,200);assert.equal(((await r.json()) as {sources:unknown[]}).sources.length,0);
r=await request('/api/analyze','POST',{text});assert.equal(((await r.json()) as {similarity:null}).similarity,null);
r=await request('/api/sources','POST',{name:'Solar source',text});assert.equal(r.status,201);const {id}=await r.json() as {id:string};
r=await request('/api/sources','POST',{name:'Duplicate',text});assert.equal(r.status,409);
const cache=new DatabaseSync(dbpath);cache.prepare('INSERT INTO web_sources (id,name,url,content,retrieved) VALUES (?,?,?,?,?)').run('web1','Solar source','https://en.wikipedia.org/wiki/Solar',text,new Date().toISOString());cache.close();
r=await request('/api/analyze','POST',{text});assert.equal(((await r.json()) as {exactPercent:number}).exactPercent,100);
const persisted=new DatabaseSync(dbpath);assert.equal(persisted.prepare('SELECT COUNT(*) AS n FROM reference_sources').get()!.n,1);persisted.close();
r=await request('/api/analyze','POST',{text:'short'});assert.equal(r.status,400);
r=await fetch(base+'/api/sources',{method:'POST',headers:{Origin:'https://untrusted.example','Content-Type':'application/json'},body:JSON.stringify({name:'x',text})});assert.equal(r.status,409);
r=await request('/');assert.equal(r.status,200);assert.ok((await r.text()).includes('/assets/'));
r=await request('/pdf.worker.min.mjs');assert.equal(r.status,200);
r=await request('/api/sources','DELETE',{id});assert.equal(r.status,200);r=await request('/api/sources');assert.equal(((await r.json()) as {sources:unknown[]}).sources.length,0);
const longText=Array.from({length:50000},(_,i)=>'term'+i).join(' ');
r=await request('/api/sources','POST',{name:'50,000-word source',text:longText});assert.equal(r.status,201);
const cache2=new DatabaseSync(dbpath);cache2.prepare('UPDATE web_sources SET content=? WHERE id=?').run(longText,'web1');cache2.close();
r=await request('/api/analyze','POST',{text:longText});const largeReport=await r.json() as {words:number;exactPercent:number};assert.equal(r.status,200);assert.equal(largeReport.words,50000);assert.equal(largeReport.exactPercent,100);
r=await request('/api/analyze','POST',{text:longText+' extra'});assert.equal(r.status,400);
console.log('14 integration checks passed, including the 50,000-word HTTP round trip.');
}finally{child.kill('SIGTERM');await new Promise(resolve=>child.once('exit',resolve));await rm(dir,{recursive:true,force:true});}});
